name: okito
description: Your best flutter coding friend. All in one flutter helper with state, route, navigation, localization, dependency injection and local storage management!
version: 1.3.0
homepage: https://github.com/ragokan/okito
repository: https://github.com/ragokan/okito

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^2.0.0
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
